[package]
name = "Compilo"
version = "0.1.0"
authors = ["Woomy4680-exe <57042741+Woomy4680-exe@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
